### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by alexmplays** [GRGServer/SAMPRacing#1]
There are some missing files please update the whole repo and add all the missing files such as:

/structures/E_CHECKPOINT.inc"

:100:  :+1:  the whole project looks dope so far and all the way you scripted.

**Comment by AeroxToby** [comment]
Doesent Missing. You Lust be make self the checkpoints 
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit 1&1 Mail gesendet.Am 08.09.17, 01:52, Alex Magana <notifications@github.com> schrieb:
There are some missing files please update the whole repo and add all the missing files such as:
/structures/E_CHECKPOINT.inc"
💯  👍  the whole project looks dope so far and all the way you scripted.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/GRGServer/SAMPRacing","title":"GRGServer/SAMPRacing","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/GRGServer/SAMPRacing"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Missing Files (#1)"}],"action":{"name":"View Issue","url":"https://github.com/GRGServer/SAMPRacing/issues/1"}}}

**Comment by Programie** [comment]
I think you are right, that file is really missing. I will try to recover it.

**Comment by alexmplays** [comment]
Excellent :D i cant wait!

**Comment by Programie** [comment]
I've fixed the issue. The main.inc was not up-to-date, so it referenced old files and missed some newer files.
The issue didn't show up in the Travis CI build because the main.inc is automatically built there, so I didn't noticed it.
